#!/usr/bin/env bash
# Turns .env and mqtt-users.conf into the config files Mosquitto reads.
# Called automatically by ./sitesync start and ./sitesync apply.
# Safe to run repeatedly; it only rewrites files it owns.
set -euo pipefail

# If anything below fails, say so plainly rather than stopping silently.
trap 'echo "" >&2; echo "Could not finish applying the MQTT settings. Nothing was started." >&2; echo "Run ./sitesync doctor, or ask for help with the message above." >&2' ERR

CONF_D=configuration/mosquitto/conf.d
PASSWD=configuration/mosquitto/config/passwd
ACL=configuration/mosquitto/config/acl
USERS=mqtt-users.conf
MOSQ_IMAGE="eclipse-mosquitto:${MOSQUITTO_VERSION:-2}"

mkdir -p "$CONF_D" certs
rm -f "$CONF_D"/*.conf 2>/dev/null || true

randpw() {  # random password; avoids SIGPIPE under `set -o pipefail`
  local s=""
  while (( ${#s} < ${1:-24} )); do
    s+="$(head -c 64 /dev/urandom | LC_ALL=C tr -dc 'A-Za-z0-9')"
  done
  printf '%s' "${s:0:${1:-24}}"
}

set_password() {  # set_password <user> <plaintext>
  local flag=""
  [[ -f "$PASSWD" ]] || flag="-c"
  # mosquitto_passwd runs as root inside the container and creates the file
  # 0600 root:root. The broker then drops to the 'mosquitto' user and cannot
  # read it -- "Unable to open pwfile" and the container restarts forever. So
  # hand it to that user in the same step, while we are still root.
  docker run --rm -v "$PWD/configuration/mosquitto/config:/mosquitto/config" \
    "$MOSQ_IMAGE" sh -euc '
      mosquitto_passwd -b $0 /mosquitto/config/passwd "$1" "$2" >/dev/null
      chown mosquitto:mosquitto /mosquitto/config/passwd 2>/dev/null \
        || chown 1883:1883 /mosquitto/config/passwd
      chmod 640 /mosquitto/config/passwd
    ' "$flag" "$1" "$2"
}

# Turn a role name into Mosquitto permission lines. This is the whole point of
# roles: nobody should ever have to write these by hand.
acl_for_role() {  # acl_for_role <role>
  local role="$1" region="${REGION:-+}"
  case "$role" in
    admin)
      echo "topic readwrite #" ;;
    integration)
      echo "topic read application/#" ;;
    integration-rw)
      echo "topic read application/#"
      echo "topic write application/+/device/+/command/#" ;;
    gateway)
      echo "topic write $region/gateway/+/event/#"
      echo "topic write $region/gateway/+/state/#"
      echo "topic read  $region/gateway/+/command/#" ;;
    gateway:*)
      local eui="${role#gateway:}"
      echo "topic write $region/gateway/$eui/event/#"
      echo "topic write $region/gateway/$eui/state/#"
      echo "topic read  $region/gateway/$eui/command/#" ;;
    *)
      return 1 ;;
  esac
}

# ---------------------------------------------------------------- login ------
if [[ "${MQTT_AUTH_ENABLED:-true}" == "true" ]]; then
  if [[ -z "${MQTT_USERNAME:-}" || -z "${MQTT_PASSWORD:-}" ]]; then
    echo "MQTT_AUTH_ENABLED is true but MQTT_USERNAME or MQTT_PASSWORD is empty in .env." >&2
    echo "Either fill both in, or set MQTT_AUTH_ENABLED=false." >&2
    exit 1
  fi

  cat > "$CONF_D/10-auth.conf" <<'EOF'
# Generated from .env by ./sitesync apply -- edits here are overwritten.
allow_anonymous false
password_file /mosquitto/config/passwd
acl_file /mosquitto/config/acl
EOF

  [[ -f "$USERS" ]] || cp mqtt-users.conf.example "$USERS"

  # ChirpStack's own internal login always exists and always has full access.
  set_password "$MQTT_USERNAME" "$MQTT_PASSWORD"

  {
    echo "# Generated by ./sitesync apply from mqtt-users.conf -- do not edit."
    echo "# Change what someone can do by changing their ROLE, then run apply."
    echo
    echo "# ChirpStack itself (username comes from .env)"
    echo "user $MQTT_USERNAME"
    acl_for_role admin
    echo
  } > "$ACL"

  KNOWN=("$MQTT_USERNAME")
  NEW_PASSWORDS=""
  while read -r user role _; do
    [[ -z "${user:-}" || "${user:0:1}" == "#" ]] && continue
    if ! LINES="$(acl_for_role "$role" 2>/dev/null)"; then
      echo "mqtt-users.conf: '$user' has an unknown role '$role'." >&2
      echo "Valid roles: integration, integration-rw, gateway, gateway:EUI" >&2
      exit 1
    fi
    KNOWN+=("$user")
    { echo "user $user"; printf '%s\n' "$LINES"; echo; } >> "$ACL"

    # A user listed here but with no password yet is new. Give them one and
    # show it once -- it is stored hashed and cannot be recovered later.
    if ! grep -q "^$user:" "$PASSWD" 2>/dev/null; then
      pw="$(randpw)"
      set_password "$user" "$pw"
      NEW_PASSWORDS+="    $user  ($role)  password: $pw"$'\n'
    fi
  done < "$USERS"

  # Anyone whose line was deleted from mqtt-users.conf loses their login.
  if [[ -f "$PASSWD" ]]; then
    while IFS=: read -r existing _; do
      [[ -z "$existing" ]] && continue
      keep=0
      for k in "${KNOWN[@]}"; do [[ "$k" == "$existing" ]] && keep=1 && break; done
      if (( ! keep )); then
        docker run --rm -v "$PWD/configuration/mosquitto/config:/mosquitto/config" \
          "$MOSQ_IMAGE" sh -euc '
            mosquitto_passwd -D /mosquitto/config/passwd "$1" >/dev/null 2>&1 || true
            chown mosquitto:mosquitto /mosquitto/config/passwd 2>/dev/null \
              || chown 1883:1883 /mosquitto/config/passwd
            chmod 640 /mosquitto/config/passwd
          ' _ "$existing" || true
        echo "  Removed MQTT user '$existing' (no longer listed in mqtt-users.conf)."
      fi
    done < "$PASSWD"
  fi

  # The ACL holds usernames and topic patterns, no secrets, and the broker
  # must be able to read it whatever the operator's umask happens to be.
  chmod 644 "$ACL" 2>/dev/null || true

  if [[ -n "$NEW_PASSWORDS" ]]; then
    printf '\n\033[1m  New MQTT passwords -- copy these now, they cannot be shown again\033[0m\n'
    printf '%s' "$NEW_PASSWORDS"
    printf '  If one is lost, anyone can run:  ./sitesync mqtt reset NAME\n\n'
  fi
else
  cat > "$CONF_D/10-auth.conf" <<'EOF'
# Generated from .env by ./sitesync apply -- edits here are overwritten.
# MQTT_AUTH_ENABLED=false: anyone who can reach the port may connect.
allow_anonymous true
EOF
  rm -f "$PASSWD" "$ACL" 2>/dev/null || true
fi

# ------------------------------------------------------------ encryption -----
case "${MQTT_TLS:-off}" in
  off) : ;;
  self-signed)
    if [[ ! -f certs/mqtt-cert.pem || ! -f certs/mqtt-key.pem ]]; then
      echo "Creating a self-signed MQTT certificate for ${SITE_DOMAIN:-localhost} ..."
      # Deliberately no container fallback here. Pulling an image to do this
      # would reach the internet, and these machines often have none -- the
      # failure would appear only at a customer site. openssl ships with
      # Ubuntu Server.
      command -v openssl >/dev/null 2>&1 || {
        echo "MQTT_TLS=self-signed needs the 'openssl' command, which is not installed." >&2
        echo "  Install it:   sudo apt-get install -y openssl" >&2
        echo "  Or set MQTT_TLS=off in .env if you do not need encrypted MQTT." >&2
        exit 1
      }
      openssl req -x509 -newkey rsa:2048 -nodes -days 3650 \
        -keyout certs/mqtt-key.pem -out certs/mqtt-cert.pem \
        -subj "/CN=${SITE_DOMAIN:-localhost}" \
        -addext "subjectAltName=DNS:${SITE_DOMAIN:-localhost}" 2>/dev/null
      cp certs/mqtt-cert.pem certs/mqtt-ca.pem
      chmod 600 certs/mqtt-key.pem 2>/dev/null || true
      echo "Done. Copy certs/mqtt-ca.pem onto each client so it trusts this broker."
    fi
    ;;
  custom)
    for f in mqtt-cert.pem mqtt-key.pem mqtt-ca.pem; do
      [[ -f "certs/$f" ]] || { echo "MQTT_TLS=custom but certs/$f is missing." >&2; exit 1; }
    done
    ;;
  *)
    echo "MQTT_TLS in .env must be one of: off, self-signed, custom (found '${MQTT_TLS}')." >&2
    exit 1 ;;
esac

if [[ "${MQTT_TLS:-off}" != "off" ]]; then
  cat > "$CONF_D/20-tls.conf" <<'EOF'
# Generated from .env by ./sitesync apply -- edits here are overwritten.
# The plain listener on 1883 stays enabled so clients can be migrated one at a
# time. Remove it from mosquitto.conf once every client uses 8883.
listener 8883
protocol mqtt
cafile   /mosquitto/certs/mqtt-ca.pem
certfile /mosquitto/certs/mqtt-cert.pem
keyfile  /mosquitto/certs/mqtt-key.pem
require_certificate false
EOF
fi
